[package]
name = "procede"
version = "0.0.1"
authors = []

[lib]
crate-type = ["cdylib"]

[dependencies]
assert_approx_eq = "1.1.0"
cgmath = "0.17.0"
lru-cache = "0.1.2"
noise = "0.5.1"
num-traits = "0.2"
wasm-bindgen = "0.2"
